name: test
on:
  pull_request:
  push:
    branches:
      - "master"
jobs:
  test:
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7']
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: SAMPLE_AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: SAMPLE_AWS_SECRET_ACCESS_KEY
      AWS_REGION: ap-northeast-1
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rspec
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - "8000:8000"
        env:
          AWS_ACCESS_KEY_ID: SAMPLE_AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: SAMPLE_AWS_SECRET_ACCESS_KEY
          AWS_REGION: ap-northeast-1
